from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_SECTION
from docx.enum.style import WD_STYLE_TYPE
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from pathlib import Path

OUT = Path('Integrated Healthcare Service Management Web Application - Complete Project Documentation.docx')

def shade(cell, fill):
    tcPr = cell._tc.get_or_add_tcPr(); shd = OxmlElement('w:shd'); shd.set(qn('w:fill'), fill); tcPr.append(shd)

def border(cell, color='D9E2F3'):
    tcPr = cell._tc.get_or_add_tcPr(); b = OxmlElement('w:tcBorders')
    for side in ('top','left','bottom','right'):
        x = OxmlElement('w:' + side); x.set(qn('w:val'),'single'); x.set(qn('w:sz'),'4'); x.set(qn('w:color'),color); b.append(x)
    tcPr.append(b)

def set_cell_text(cell, value, bold=False):
    cell.text = ''
    p=cell.paragraphs[0]; r=p.add_run(str(value)); r.bold=bold; r.font.size=Pt(8.5); p.paragraph_format.space_after=Pt(0)
    cell.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER; border(cell)

def field(paragraph, code):
    run=paragraph.add_run(); begin=OxmlElement('w:fldChar'); begin.set(qn('w:fldCharType'),'begin')
    instr=OxmlElement('w:instrText'); instr.set(qn('xml:space'),'preserve'); instr.text=code
    sep=OxmlElement('w:fldChar'); sep.set(qn('w:fldCharType'),'separate'); end=OxmlElement('w:fldChar'); end.set(qn('w:fldCharType'),'end')
    run._r.extend([begin,instr,sep,end])

def page_number(paragraph): field(paragraph, 'PAGE')

d=Document()
sec=d.sections[0]; sec.top_margin=Inches(.8); sec.bottom_margin=Inches(.75); sec.left_margin=Inches(.85); sec.right_margin=Inches(.85)
styles=d.styles
styles['Normal'].font.name='Aptos'; styles['Normal'].font.size=Pt(10.5); styles['Normal']._element.rPr.rFonts.set(qn('w:eastAsia'),'Aptos')
styles['Normal'].paragraph_format.line_spacing=1.25; styles['Normal'].paragraph_format.space_after=Pt(7)
for style,size,color in [('Title',23,'0B4F6C'),('Heading 1',16,'0B4F6C'),('Heading 2',13,'176B87'),('Heading 3',11,'176B87')]:
    s=styles[style]; s.font.name='Aptos Display'; s.font.size=Pt(size); s.font.color.rgb=RGBColor.from_string(color); s.font.bold=True
    s.paragraph_format.space_before=Pt(14); s.paragraph_format.space_after=Pt(7)
if 'Caption' in styles: styles['Caption'].font.name='Aptos'; styles['Caption'].font.size=Pt(9); styles['Caption'].font.italic=True
header=sec.header.paragraphs[0]; header.text='INTEGRATED HEALTHCARE SERVICE MANAGEMENT WEB APPLICATION'; header.alignment=WD_ALIGN_PARAGRAPH.CENTER
header.runs[0].font.size=Pt(8); header.runs[0].font.color.rgb=RGBColor.from_string('5D7480')
footer=sec.footer.paragraphs[0]; footer.alignment=WD_ALIGN_PARAGRAPH.CENTER; footer.add_run('Project Documentation  |  '); page_number(footer); footer.runs[0].font.size=Pt(8)

def p(text='', style=None, align=None):
    x=d.add_paragraph(style=style); x.add_run(text)
    if align is not None: x.alignment=align
    return x
def heading(text, level=1): return d.add_heading(text, level=level)
def bullet(text): return p(text,'List Bullet')
def placeholder(label, caption, explanation='Insert the verified project artefact here. Do not use a mock or illustrative image.'):
    x=p(label, align=WD_ALIGN_PARAGRAPH.CENTER); x.runs[0].bold=True; x.runs[0].font.color.rgb=RGBColor.from_string('7A4E00')
    y=p(caption,'Caption',WD_ALIGN_PARAGRAPH.CENTER); y.runs[0].bold=True
    p(explanation,'Caption',WD_ALIGN_PARAGRAPH.CENTER)
def table(headers, rows, widths=None):
    t=d.add_table(rows=1, cols=len(headers)); t.style='Table Grid'; t.alignment=WD_TABLE_ALIGNMENT.CENTER
    for i,h in enumerate(headers): set_cell_text(t.rows[0].cells[i],h,True); shade(t.rows[0].cells[i],'0B4F6C');
    for c in t.rows[0].cells:
        for r in c.paragraphs[0].runs: r.font.color.rgb=RGBColor(255,255,255)
    for row in rows:
        cells=t.add_row().cells
        for i,v in enumerate(row): set_cell_text(cells[i],v)
    if widths:
        for row in t.rows:
            for i,w in enumerate(widths): row.cells[i].width=Inches(w)
    d.add_paragraph('')
    return t
def chapter(title):
    d.add_page_break(); heading(title,1)
def auto_list(title, code, prompt):
    heading(title,1); q=p(prompt); q.runs[0].italic=True; field(p(),code)

# Preliminary pages
p('DESIGN AND DEVELOPMENT OF AN', 'Title', WD_ALIGN_PARAGRAPH.CENTER)
p('INTEGRATED HEALTHCARE SERVICE MANAGEMENT WEB APPLICATION','Title',WD_ALIGN_PARAGRAPH.CENTER)
p('',align=WD_ALIGN_PARAGRAPH.CENTER)
p('A Project Report Submitted to the [INSERT DEPARTMENT] in Partial Fulfilment of the Requirements for the Award of [INSERT DEGREE/PROGRAMME]','Normal',WD_ALIGN_PARAGRAPH.CENTER)
p('\n\nBy','Normal',WD_ALIGN_PARAGRAPH.CENTER)
p('[INSERT STUDENT FULL NAME]','Heading 2',WD_ALIGN_PARAGRAPH.CENTER)
p('[INSERT INDEX/MATRICULATION NUMBER]','Normal',WD_ALIGN_PARAGRAPH.CENTER)
p('\nSupervisor: [INSERT SUPERVISOR NAME]','Normal',WD_ALIGN_PARAGRAPH.CENTER)
p('[INSERT UNIVERSITY NAME]\n[INSERT FACULTY/DEPARTMENT]\n[INSERT MONTH AND YEAR]','Normal',WD_ALIGN_PARAGRAPH.CENTER)
d.add_page_break()
heading('Declaration',1); p('I declare that this report is my original work, prepared under the guidance of the named supervisor. Except where sources are acknowledged, it has not been submitted in whole or in part for another award. The software artefacts, screenshots, repository information and deployment details inserted into the final copy must accurately represent the project submitted.')
p('Student signature: ____________________    Date: ____________________')
heading('Certification / Approval',1); p('This report has been examined and approved as meeting the requirements of [INSERT PROGRAMME/DEPARTMENT], subject to the institution’s regulations.')
p('Supervisor: [INSERT NAME]  Signature: ____________________  Date: ____________________\nHead of Department: [INSERT NAME]  Signature: ____________________  Date: ____________________')
heading('Dedication',1); p('[INSERT PERSONAL DEDICATION.]')
heading('Acknowledgement',1); p('I sincerely acknowledge the guidance of [INSERT SUPERVISOR NAME], the support of the lecturers and staff of [INSERT DEPARTMENT], and the encouragement received from family, colleagues and friends. I also acknowledge the official documentation and public resources cited in this report.')
heading('Abstract',1); p('This project presents the design and development of an Integrated Healthcare Service Management Web Application. The application centralises common patient-facing and administrative activities, including registration, appointment scheduling, queue management, provider discovery, consultation support, pharmacy ordering, laboratory bookings, records, reminders, family-member management, notifications and reporting. It is a responsive web application; a mobile application is outside the scope of the present implementation. The implemented application uses Python and Flask with Jinja templates, SQLAlchemy, a local SQLite database configuration, Bootstrap-based responsive presentation and a Vercel deployment configuration. The codebase also contains support for authentication, session management, language preferences, JSON-backed translation catalogues and selected real-time communication components.\n\nThe study adopts an Agile development approach to allow the modules to be developed and reviewed iteratively. The report documents requirements, architecture, data entities, interfaces, verification activities and deployment considerations. Features described as available in source code are distinguished from configuration-dependent, simulated or future integrations. In particular, the conversational helper and symptom-checking components provide general informational guidance only; they do not diagnose conditions, prescribe treatment or replace consultation with a qualified healthcare professional. Full-language coverage remains a verification requirement: every visible string, form message, validation message, notification and chatbot text must be audited in each supported language before release. The project demonstrates how a modular web platform can improve access to coordinated healthcare-service information while retaining clear operational and clinical-safety boundaries.')
auto_list('Table of Contents','TOC \\o "1-3" \\h \\z \\u','Update this field in Microsoft Word (right-click → Update Field) after final pagination.')
auto_list('List of Figures','TOC \\h \\z \\c "Figure"','Update this field after screenshots and diagrams have been inserted and captioned.')
auto_list('List of Tables','TOC \\h \\z \\c "Table"','Update this field after final tables have been confirmed.')
heading('List of Abbreviations',1)
table(['Abbreviation','Meaning'],[['AI','Artificial Intelligence'],['API','Application Programming Interface'],['DBMS','Database Management System'],['ERD','Entity Relationship Diagram'],['JWT','JSON Web Token'],['ORM','Object-Relational Mapping'],['SOS','Emergency assistance request'],['UI','User Interface'],['UX','User Experience']])

chapter('CHAPTER ONE: INTRODUCTION')
heading('1.1 Background of the Study',2); p('Healthcare service delivery involves recurring coordination tasks: identifying a provider, reserving a suitable time, arriving at the facility, monitoring a queue, obtaining follow-up information and managing related services. When these activities are disconnected, patients may need to repeat information or use separate channels for appointments, pharmacy requests, laboratory services and support. Digital health systems can help organise these interactions when they are designed around people, workflows, privacy and local clinical governance. The World Health Organization identifies digital health as an important part of health-system transformation, while also recognising that implementation must be guided by appropriate strategy, resources and governance [1].\n\nThe project responds to this context through a single responsive web application. It offers role-based patient, provider and administrator workflows and consolidates service-related tasks into a shared interface. The application is intended as a service-management platform, not an electronic substitute for clinical judgement. Medical decisions remain the responsibility of qualified professionals and approved institutional processes.')
heading('1.2 Problem Statement',2); p('Patients can experience difficulty coordinating appointments, clinic queues, provider information, follow-up tasks and supporting services through fragmented manual or disconnected digital processes. Service staff likewise require timely visibility of bookings, queues, users, inventory-related requests and announcements. A web-based platform that brings these functions together can improve information access and workflow visibility; however, it must do so without overstating automation, compromising personal data or presenting informational AI outputs as clinical advice.')
heading('1.3 Aim of the Study',2); p('The aim is to design and develop an integrated healthcare service management web application that provides a coordinated, accessible and role-based interface for healthcare-service activities.')
heading('1.4 Objectives of the Study',2)
for x in ['Develop secure account registration, login and role-based access workflows.','Provide appointment booking, rescheduling, cancellation and provider-availability functions.','Support queue joining, status management and estimated-wait visibility.','Provide provider directory, profile and review functions.','Integrate service modules for records, laboratory requests, pharmacy requests, reminders, family members, notifications and billing records.','Provide information-oriented symptom and conversational helper interfaces with explicit clinical-safety limitations.','Implement multilingual presentation so that all user-facing text is translated consistently across supported interfaces.','Provide administrative capabilities for users, providers, queues, pharmacy stock, announcements and analytics.','Deploy the web application using the project’s Vercel configuration and maintain the source using Git and GitHub.']: bullet(x)
heading('1.5 Significance of the Study',2); p('For patients, the platform provides a single point of access to service information and self-service tasks. For providers and administrators, it provides structured views of bookings, queues and selected operational records. For the project, it demonstrates practical application of web engineering concepts including authentication, database modelling, responsive design, localisation and deployment. Its multilingual approach is an accessibility feature because it seeks to make the complete interface—not merely navigation labels—understandable to users with different language preferences.')
heading('1.6 Scope of the Study',2); p('The scope is a web application. Source-code evidence supports modules for user accounts; patient, doctor and administrator roles; appointments and slots; queues; profiles; records; laboratory bookings; pharmacy catalogue and orders; billing records; family members; reminders; vaccinations; insurance profiles; emergency alerts; chat consultations; reviews; notifications; announcements; analytics; and language preferences. The project includes Vercel configuration for web deployment. A dedicated native mobile application, live clinical-device integration, a production payment-gateway integration and a production-grade generative-AI integration are not evidenced by the inspected repository and are therefore outside the confirmed implementation scope.')
heading('1.7 Limitations of the Study',2); p('The application depends on network access and correct server-side configuration. The checked payment endpoint marks an appointment as paid and generates a reference in application data; no external payment-provider integration is evidenced and it must not be represented as live financial processing. Email delivery depends on SMTP environment variables. The configured local database is SQLite, while Vercel serverless storage requires an externally configured database for durable production data. Translation files exist for supported locales, but completeness of every text string requires a release audit. AI-labelled helper functions are rule-based/informational in the inspected source and require validation, escalation rules and governance before any clinical deployment.')
heading('1.8 Organization of the Report',2); p('Chapter One introduces the project. Chapter Two reviews related digital-health platforms and the identified gap. Chapter Three describes requirements and methodology. Chapter Four presents the design and implementation. Chapter Five defines testing and evaluation. Chapter Six concludes the report and proposes future work.')

chapter('CHAPTER TWO: LITERATURE REVIEW')
heading('2.1 Introduction',2); p('This chapter situates the proposed application within digital healthcare and patient-service management. It uses public, official sources for platform descriptions and avoids feature claims that cannot be supported by those sources.')
heading('2.2 Digital Healthcare Systems',2); p('Digital healthcare systems use information and communication technologies to support health-related information, service delivery and management. Their value depends on more than a user interface: appropriate governance, privacy safeguards, usable workflows, accessible language and integration with responsible clinical processes are essential. WHO’s global strategy frames digital health as a means to support health outcomes and health-system priorities, not as a stand-alone solution [1].')
heading('2.3 Healthcare Service Management Systems',2); p('Healthcare service management systems coordinate operational interactions such as scheduling, check-in, queue visibility, communication and service requests. A well-designed system separates access control by role, maintains an auditable data model and presents task-focused interfaces. It should also communicate limitations clearly: operational convenience does not itself confirm medical accuracy or clinical appropriateness.')
heading('2.4 Existing Healthcare Applications',2); p('MyChart is a patient portal product with documented support for scheduling and managing appointments, provider discovery, family access, medical-record viewing/sharing, billing-related functions and virtual-care options, subject to the participating organisation’s configuration [2–5]. Practo and Apollo 24/7 are relevant regional consumer-health platforms; the features available to a user can vary by geography, provider, service category and current product configuration. Their exact comparable functionality should be verified against the official pages applicable to the project’s intended deployment country before final submission. This study uses them as contextual examples rather than asserting an exhaustive feature set.')
heading('2.5 Comparison of Existing Systems',2)
table(['Table 2.1: System','Appointments','Records / family','Virtual care','Pharmacy / lab','Evidence note'],[['MyChart','Documented','Documented','Documented','Configuration-dependent','Official MyChart feature pages [2–5].'],['Practo','[VERIFY FOR TARGET MARKET]','[VERIFY]','[VERIFY]','[VERIFY]','Verify current official pages before final submission.'],['Apollo 24/7','[VERIFY FOR TARGET MARKET]','[VERIFY]','[VERIFY]','[VERIFY]','Verify current official pages before final submission.'],['Proposed system','Implemented booking, reschedule/cancel routes','Implemented records and family-member entities/routes','Telemedicine and chat modules present','Pharmacy and lab modules present','Repository inspection; external fulfilment/integration not confirmed.']],[1.1,1.0,1.1,1.1,2.6])
heading('2.6 Limitations/Gaps in Existing Systems',2); p('A platform may be comprehensive within a particular healthcare network yet not provide a unified experience across independently managed services. Conversely, a broad consumer platform may not match the workflows, language needs or governance requirements of a local setting. The gap addressed by this project is a configurable, role-based web interface that gathers appointment, queue, service-request, communication and accessibility functions in a coherent design. It is not a claim that the project replaces mature clinical information systems or their regulatory controls.')
heading('2.7 Proposed Solution',2); p('The proposed solution is an integrated web application with distinct patient, provider and administrator interfaces. Its data model links user accounts to provider information, appointment and queue records, service requests, reminders and notifications. Multilingual preferences are stored per patient and JSON translation catalogues are used to render translated interface text. The solution also reserves clear boundaries for integrations that require external authority: payment processing, durable cloud database, clinical records interoperability and clinically validated AI are configuration or future-work matters rather than confirmed built-in services.')
heading('2.8 Summary',2); p('The review supports an integrated approach to patient-service coordination. The proposed platform focuses on coherent web workflows, operational transparency and multilingual accessibility while retaining the distinction between software assistance and professional healthcare delivery.')

chapter('CHAPTER THREE: SYSTEM ANALYSIS AND METHODOLOGY')
heading('3.1 Introduction',2); p('This chapter defines the system’s users, requirements and development approach. Requirements are derived from the inspected repository and the project brief; items needing operational confirmation are explicitly marked.')
heading('3.2 Development Methodology',2); p('Agile development is suitable because the application contains interdependent modules that benefit from incremental delivery and feedback. A practical cycle is: prioritise a workflow; model its data; implement the route and template; test permissions and error paths; review usability; and refine the backlog. For this project, early increments can cover authentication, appointments and queues; later increments can cover records, pharmacy, laboratory, communication, localisation and administration. Each iteration should end with demonstrable acceptance criteria and a record of unresolved risks.')
heading('3.3 Requirement Analysis',2); p('Stakeholder needs were organised into patient access, provider workflow, administration, safety, privacy, accessibility and deployment. The key analysis principle is traceability: each requirement should map to an interface, route or data entity, and later to a test case. Requirements labelled “confirm” should be validated against the deployed application, not inferred from a template or mock-up.')
heading('3.4 Functional Requirements',2)
table(['ID','Requirement','Priority','Evidence / acceptance criterion'],[['FR-01','Register, authenticate and log out users by role.','High','Registration/login routes; role checks; valid credentials create session.'],['FR-02','Manage provider profiles and availability slots.','High','Doctor and AppointmentSlot entities; provider routes.'],['FR-03','Book, reschedule, cancel and view appointments.','High','Appointment routes; status and payment fields.'],['FR-04','Join and manage a consultation queue.','High','QueueRecord entity and queue action routes.'],['FR-05','Request pharmacy and laboratory services.','High','PharmacyMedicine/Order and LabTestBooking modules.'],['FR-06','Maintain records, reminders, family members and notifications.','High','Corresponding models/routes.'],['FR-07','Provide informational symptom and chat assistance.','Medium','AI helper routes; must show clinical disclaimer.'],['FR-08','Translate all visible user-facing content.','High','Language preferences and translation catalogues; verify coverage.'],['FR-09','Provide administrative user, provider, queue, pharmacy, announcement and analytics views.','High','Admin routes/templates and analytics route.']])
heading('3.5 Non-Functional Requirements',2)
table(['ID','Requirement','Measure / verification'],[['NFR-01','Security','Password hashing, authenticated routes and role checks are present; conduct security review before release.'],['NFR-02','Usability','Responsive Bootstrap interface; task testing with representative users.'],['NFR-03','Performance','Common pages should load within [INSERT TARGET] under [INSERT TEST LOAD].'],['NFR-04','Availability','Vercel deployment configuration; confirm uptime/monitoring arrangement.'],['NFR-05','Accessibility','Keyboard, contrast, labels and complete multilingual coverage to be tested.'],['NFR-06','Maintainability','Flask routes, Jinja templates and SQLAlchemy models are separated.'],['NFR-07','Privacy','Least-privilege access, secure configuration and data-retention policy require confirmation.']])
heading('3.6 System Users/Roles',2); p('Patient/User: registers, manages profile and family members, books appointments, joins queues, requests services, reviews records, receives notifications and accesses informational tools.\n\nHealthcare Provider: manages availability, views appropriate appointments and queue entries, records consultation-related notes where authorised, and participates in configured consultation workflows.\n\nAdministrator: manages users, providers, walk-ins, pharmacy items, announcements, queue actions and analytics. Administrative access must be restricted and audited in a production deployment.')
heading('3.7 Hardware Requirements',2); table(['Component','Minimum','Recommended'],[['Client device','Modern browser-capable computer','Current desktop/laptop with stable internet'],['Server/runtime','Vercel-compatible Python serverless runtime','Managed production environment with monitoring'],['Storage','Development SQLite file','Managed persistent database for production'],['Network','Internet connection','Reliable broadband with TLS-enabled deployment']])
heading('3.8 Software Requirements',2); p('Confirmed repository technologies: Python; Flask 3.0.3; Jinja2; Flask-SQLAlchemy/SQLAlchemy; Flask-Login; Flask-Babel/Babel; Bootstrap 5.1.3 loaded by template; Font Awesome loaded by template; optional Flask-SocketIO/socket.io client support; PyJWT; SQLite in the default local configuration; optional PostgreSQL when `DATABASE_URL` is supplied; Git and GitHub; and Vercel via `vercel.json`. [INSERT CONFIRM PYTHON VERSION USED FOR SUBMISSION.]')
heading('3.9 Use Case Analysis',2); p('The primary use cases are: register/login; browse providers; book/reschedule/cancel appointment; join/check queue; request laboratory or pharmacy service; view records and reminders; manage family member data; receive notifications; conduct configured chat/telemedicine workflow; and administer users, providers, queues, stock, announcements and reports. Each use case is constrained by authenticated role and ownership checks.')
heading('3.10 Use Case Diagram',2); placeholder('[INSERT USE CASE DIAGRAM HERE]','Figure 3.1: Use Case Diagram','Show Patient, Healthcare Provider and Administrator actors, with their principal interactions and authenticated boundaries.')
heading('3.11 System Flow',2); p('A patient registers and signs in, then selects a provider or service. For appointments, the application retrieves available slots, validates the request and stores an appointment with status information. A patient may later reschedule, cancel, pay through the currently implemented internal payment-status flow, or check in/join a queue where permitted. Staff and administrators update relevant records; notifications and dashboard summaries present the current state. Language selection is resolved from the authenticated preference or session/cookie setting, then the application retrieves translations from the selected catalogue. Sensitive functions should reject unauthorised requests and log relevant operational events [INSERT CONFIRM LOGGING POLICY].')
heading('3.12 Summary',2); p('The analysis establishes a modular, role-based system whose critical requirements are appointment coordination, queue visibility, service access, multilingual accessibility and safe information boundaries. Agile iterations support progressively verifying these requirements.')

chapter('CHAPTER FOUR: SYSTEM DESIGN AND IMPLEMENTATION')
heading('4.1 Introduction',2); p('This chapter describes the confirmed implementation structure and the intended user interfaces. Screenshots must be replaced with genuine captures of the deployed or locally running application, annotated only after their content has been verified.')
heading('4.2 System Architecture',2); p('The application follows a server-rendered web architecture. A browser sends HTTP requests to Flask routes. Flask applies authentication and role checks, renders Jinja templates and persists data through SQLAlchemy. The default non-serverless configuration uses SQLite; the code accepts a PostgreSQL `DATABASE_URL` when supplied. Static assets and JSON translation files support the interface. A Vercel configuration builds `app.py` using `@vercel/python` and routes requests to the application. Socket.IO imports and client assets are present for chat-oriented features, but production real-time behaviour should be validated in the Vercel environment before it is claimed.')
placeholder('[INSERT SYSTEM ARCHITECTURE DIAGRAM HERE]','Figure 4.1: System Architecture','Show Browser → Vercel/Flask → Authentication/Business Modules → SQLAlchemy → Persistent Database; include translation assets and optional SMTP/real-time services only if configured.')
heading('4.3 Database Design',2); p('SQLAlchemy models represent the main domain concepts. User is the central identity entity. Doctor extends provider information through a user relationship. Appointments connect patients, doctors, optional family members and payment fields; queue records connect patients and doctors. Supporting entities retain service, communication and health-management data. Foreign keys create explicit ownership and association boundaries.')
placeholder('[INSERT ER DIAGRAM HERE]','Figure 4.2: Entity Relationship Diagram','Include User, Doctor, Appointment, QueueRecord, AppointmentSlot, FamilyMember, HealthRecord, LabTestBooking, PharmacyMedicine, PharmacyOrder, ChatConsultation, ChatMessage, Notification and other implemented entities.')
heading('4.4 Database Tables',2)
table(['Table 4.1: Entity','Purpose','Key relationships'],[['User','Credentials, identity, role and profile information.','One-to-one Doctor where applicable; one-to-many patient records.'],['Doctor','Provider specialty, fee, biography, qualifications and telemedicine flag.','Belongs to User; has appointments, slots, queues and reviews.'],['Appointment','Scheduled care request, status, consultation and payment fields.','Patient User; Doctor; optional FamilyMember.'],['QueueRecord','Walk-in/consultation queue state and estimated wait.','Patient User and Doctor.'],['AppointmentSlot','Provider availability interval.','Doctor.'],['HealthRecord','Patient-uploaded record metadata and optional sharing link.','Patient User; optional Doctor.'],['LabTestBooking','Laboratory test request and status.','Patient User.'],['PharmacyMedicine / PharmacyOrder','Catalogue/inventory metadata and patient medicine order.','Order belongs to patient and medicine.'],['FamilyMember','Dependent details managed by a patient.','Patient User; optional appointments.'],['ChatConsultation / ChatMessage','Consultation topic, state and messages.','Patient, optional Doctor and sender User.'],['Notification / Announcement','Targeted messages and administrator-created announcements.','Notification recipient User; announcement creator User.'],['LanguagePreference','Persisted language and voice-assistance preference.','Patient User.']])
heading('4.5 User Interface Design',2); p('The interface uses reusable Jinja templates and Bootstrap to provide a responsive layout. Usability principles include clear page titles, task-oriented navigation, feedback messages, labelled controls, consistent status indicators and role-appropriate dashboards. All visible strings should pass through the project translation approach. The quality requirement is full interface localisation: content, headings, forms, controls, confirmations, errors, validations, notifications, footer, FAQ and chatbot interface—not navigation alone—must switch with the selected language.')

sections=[
('4.6 Home Page','[INSERT SCREENSHOT: HOME PAGE HERE]','Figure 4.3: Home Page','Demonstrate the landing-page purpose, service entry points, navigation and language control. The “Meet Our Doctors” area should be described as a directory of providers available through or discoverable via the platform, not as staff of a single hospital unless that relationship is independently confirmed.','The home page introduces the platform and directs users to account access, appointment, provider and service functions. Its content should explain the platform’s coordination role without implying ownership of the listed providers or healthcare institutions.'),
('4.7 Registration and Login','[INSERT SCREENSHOT: LOGIN PAGE HERE]','Figure 4.4: Login Page','Show the authentic credential-entry and validation interface.','Registration creates a role-aware user account and login establishes an authenticated session. Passwords are stored through Werkzeug password-hashing methods in the inspected model. Email verification and reset routes exist; SMTP delivery requires configured credentials.'),
('','[INSERT SCREENSHOT: REGISTRATION PAGE HERE]','Figure 4.5: Registration Page','Show required fields, role selection only if actually exposed, and validation feedback.',''),
('4.8 Patient Dashboard','[INSERT SCREENSHOT: DASHBOARD HERE]','Figure 4.6: Patient Dashboard','Show the current user’s appointment, queue, reminder and notification summaries.','The dashboard consolidates selected patient activities. Displayed data should be scoped to the authenticated user and should not expose another patient’s records.'),
('4.9 Appointment Management','[INSERT SCREENSHOT: APPOINTMENT BOOKING PAGE HERE]','Figure 4.7: Appointment Booking','Show provider/slot selection, details and confirmation.','Appointments link a patient, doctor and time, with status, notes, consultation type and payment fields. Reschedule and cancellation routes are present and should be demonstrated with actual test data.'),
('4.10 Queue Management','[INSERT SCREENSHOT: QUEUE TRACKING PAGE HERE]','Figure 4.8: Queue Tracking','Show queue number, current status and estimated wait.','Queue records store status, priority and estimated waiting time. “Real-time” should be claimed only after observing an actual deployed update flow; source presence alone does not prove production real-time delivery.'),
('4.11 Healthcare Provider Search and Profiles','[INSERT SCREENSHOT: PROVIDER SEARCH HERE]','Figure 4.9: Provider Search','Show search/filtering and provider cards.','Provider profiles present specialty, biography, qualifications, experience and availability-related information where entered.'),
('','[INSERT SCREENSHOT: PROVIDER PROFILE HERE]','Figure 4.10: Provider Profile','Show the authentic profile, reviews and booking route.','Reviews are stored in the DoctorReview entity. User-generated content requires moderation and governance before production use.'),
('4.12 Online Consultation','[INSERT SCREENSHOT: CONSULTATION PAGE HERE]','Figure 4.11: Online Consultation','Show chat and/or telemedicine interface as actually deployed.','ChatConsultation, ChatMessage and TelemedicineSession models/routes are present. Video, messaging delivery and clinical workflow must be confirmed in the final deployment environment.'),
('4.13 Medical Services','[INSERT SCREENSHOT: MEDICAL SERVICES PAGE HERE]','Figure 4.12: Medical Services','Show actual listed services and booking paths.','This section presents available service categories; do not describe any institution, provider or clinical service as available unless it has been configured and verified.'),
('4.14 Pharmacy','[INSERT SCREENSHOT: PHARMACY PAGE HERE]','Figure 4.13: Pharmacy','Show medicines, prescription requirement and order form.','The implementation includes medicine catalogue, stock and order entities. It is an ordering workflow; dispensing, licensing, fulfilment and payment-provider integration require separate operational confirmation.'),
('4.15 Laboratory Services','[INSERT SCREENSHOT: LABORATORY PAGE HERE]','Figure 4.14: Laboratory Services','Show test request form and request status.','LabTestBooking records a patient’s requested test, preferred date, notes and status. Laboratory collection and results integration are not assumed.'),
('4.16 Medical Records','[INSERT SCREENSHOT: MEDICAL RECORDS PAGE HERE]','Figure 4.15: Medical Records','Show records list, upload metadata and authorised download.','HealthRecord stores metadata and a file name, with optional doctor-sharing reference. Production storage, malware scanning, encryption, retention and consent controls must be confirmed.'),
('4.17 Family Account Management','[INSERT SCREENSHOT: FAMILY ACCOUNT PAGE HERE]','Figure 4.16: Family Account Management','Show dependants and permitted action controls.','FamilyMember records are linked to the managing patient. Any proxy access policy for minors or adults should be defined by the deploying institution.'),
('4.18 Payment System','[INSERT SCREENSHOT: PAYMENT PAGE HERE]','Figure 4.17: Payment Interface','Show the actual appointment payment-status interface and receipt.','The inspected payment route records a completed state, a fixed method label and an internally generated reference. It is a simulated/internal workflow, not evidence of live card processing. A verified gateway integration is required before accepting real payments.'),
('4.19 AI Health Assistant','[INSERT SCREENSHOT: AI CHATBOT HERE]','Figure 4.18: AI Health Assistant','Show the disclaimer and the actual response interface.','The application contains an AI-labelled chat endpoint and a symptom-checking route. In this report they are described as informational helpers only. They must display an explicit notice that they do not provide diagnosis, treatment or emergency advice, and must direct urgent symptoms to appropriate emergency services.'),
('4.20 Multilingual Support','[INSERT SCREENSHOT: ENGLISH VERSION HERE]','Figure 4.19: English Interface','Use the same interface state as the translated example.','The code defines English, French, Spanish, Hindi, Chinese, Korean, Twi and Hausa locale options, with JSON translation catalogues and language preferences. This supports localisation architecture, but release acceptance requires checking every user-facing string.'),
('','[INSERT SCREENSHOT: SECOND LANGUAGE VERSION HERE]','Figure 4.20: Translated Interface','Use the same page after selecting [INSERT LANGUAGE].','Language switching must change home, services, appointment and consultation pages, dashboard, forms, controls, headings, paragraphs, errors, success messages, notifications, FAQ, footer, validation feedback and chatbot text. Record any untranslated keys as defects.'),
('4.21 Notifications and Communication','[INSERT SCREENSHOT: NOTIFICATIONS/LIVE CHAT HERE]','Figure 4.21: Notifications and Communication','Show authentic notification list and communication state.','Notification, announcement, support-chat and consultation-chat routes support communication workflows. Delivery guarantees and real-time behaviour must be verified in deployment.'),
('4.22 Administrative Dashboard','[INSERT SCREENSHOT: ADMIN DASHBOARD HERE]','Figure 4.22: Administrative Dashboard','Show role-restricted operational summaries.','The administrator interface brings together control functions. It should be restricted to authorised accounts and should not expose unnecessary patient data.'),
('4.23 User Management','[INSERT SCREENSHOT: USER MANAGEMENT HERE]','Figure 4.23: User Management','Show actual user-management functionality.','Administration includes user/provider management paths. [INSERT CONFIRM WHETHER EDIT/DEACTIVATION/AUDIT FEATURES ARE IMPLEMENTED.]'),
('4.24 Appointment and Queue Management','[INSERT SCREENSHOT: ADMIN APPOINTMENT/QUEUE MANAGEMENT HERE]','Figure 4.24: Administrative Appointment and Queue Management','Show staff actions and audit-relevant state changes.','Administrators can add walk-ins and execute queue actions through protected routes. Status transitions should be validated against the intended operational policy.'),
('4.25 Reports and Analytics','[INSERT SCREENSHOT: REPORTS AND ANALYTICS HERE]','Figure 4.25: Reports and Analytics','Show current reporting metrics and filters.','An analytics route/template is present. Document only the metrics that are observable in the actual interface and state their calculation period/source.'),
('4.26 Security Implementation','[INSERT SCREENSHOT: SECURITY/ACCESS CONTROL EVIDENCE HERE]','Figure 4.26: Security and Access-Control Evidence','Show a safe, non-sensitive illustration of role-restricted access or validation.','Confirmed controls include hashed passwords, Flask-Login-protected routes, role/ownership checks, timed token utilities and JWT support. Before production, replace the development secret, enforce HTTPS, configure secure cookies, validate uploads, adopt a secure persistent database, define audit logging and complete vulnerability testing.'),
('4.27 Deployment','[INSERT SCREENSHOT: DEPLOYED WEBSITE HERE]','Figure 4.27: Deployed Healthcare Web Application','Use a genuine browser capture of the deployed Vercel URL.','The repository contains a Vercel configuration that builds `app.py` with `@vercel/python` and routes requests to it. Deployment requires the GitHub repository to be connected to Vercel, environment variables configured, and a production persistence strategy confirmed. [INSERT DEPLOYED URL.]')]
for title,label,cap,explain,body in sections:
    if title: heading(title,2)
    placeholder(label,cap,explain)
    if body: p(body)
heading('4.28 Summary',2); p('The implementation combines a Flask web backend, Jinja/Bootstrap interfaces, SQLAlchemy models and a Vercel deployment configuration. The design is intentionally modular. Confirmed code capabilities are documented separately from features that depend on external services, configuration, testing or future development.')

chapter('CHAPTER FIVE: SYSTEM TESTING AND EVALUATION')
heading('5.1 Introduction',2); p('Testing verifies that a feature meets its defined acceptance criterion and that access restrictions, messages and data state behave as expected. The “Actual Result” and “Status” fields below are deliberately left for execution evidence; they must not be marked passed without a recorded test run.')
heading('5.2 Testing Methodology',2); p('Use a layered approach: manual functional tests for user workflows; role/ownership tests for access control; usability sessions with representative users; security checks for authentication, input handling and protected files; and performance/deployment tests in an environment representative of release. Record test date, tester, build/commit identifier, browser/device, input data and evidence for each result.')
heading('5.3 Functional Testing',2)
tests=[('TC-01','Registration','Submit valid and duplicate account data.','Valid account is created; duplicate data receives a clear error.'),('TC-02','Login','Login with valid and invalid credentials.','Authorised user reaches correct dashboard; invalid login is rejected.'),('TC-03','Appointment booking','Select provider and available slot, then submit.','Appointment is stored with correct patient, provider and status.'),('TC-04','Appointment cancellation','Cancel an owned scheduled appointment.','Status/action changes according to business rule; unauthorised user is rejected.'),('TC-05','Queue tracking','Join queue and inspect position/status.','Queue record has number, status and estimated wait.'),('TC-06','Provider search','Search/browse provider records.','Matching provider profiles are displayed.'),('TC-07','Pharmacy','Place valid medicine order with prescription condition.','Order is stored; stock/prescription conditions are respected.'),('TC-08','Laboratory','Submit laboratory booking request.','Booking is stored with requested test and status.'),('TC-09','Payments','Invoke appointment payment workflow.','Internal status/reference updates; do not test with real funds unless gateway is verified.'),('TC-10','Family accounts','Add and remove authorised family-member record.','Ownership is enforced and record changes correctly.'),('TC-11','AI helper','Submit common and urgent symptom prompts.','Informational response and clear non-diagnostic/escalation notice are shown.'),('TC-12','Language switching','Switch each supported locale on representative pages.','All visible interface text is translated or defects are logged.'),('TC-13','Notifications','Create/read notification for intended user.','Notification visibility and read state are correct.'),('TC-14','Admin functions','Access management screens with admin and patient accounts.','Admin succeeds; non-admin receives denial/redirect.')]
table(['Test ID','Feature','Test Description','Expected Result','Actual Result','Status'],[[a,b,c,e,'[INSERT RESULT]','[PASS/FAIL]'] for a,b,c,e in tests],[.55,.9,2.05,2.05,1.2,.65])
heading('5.4 Usability Testing',2); p('Recruit [INSERT NUMBER] representative users and ask each to register, find a provider, book an appointment, check a queue, request a service and change language. Collect task completion, observed errors, time on task and qualitative feedback. Evaluate clarity of labels, navigation, forms, confirmation messages, mobile responsiveness and translation quality. [INSERT USABILITY RESULTS AND IMPROVEMENTS.]')
heading('5.5 Security Testing',2); p('Test unauthenticated access to protected routes; attempt cross-user access to appointments, records and payments; validate invalid login/reset tokens; inspect session-cookie attributes in production; test file-upload type/size handling; and verify that secrets are supplied by environment configuration rather than committed. Do not perform intrusive testing against systems without authorisation. [INSERT SECURITY TEST EVIDENCE AND FINDINGS.]')
heading('5.6 Performance Testing',2); p('Measure representative page and action response times under an agreed workload. Include home page, login, dashboard, appointment submission, queue update and language switch. Record network conditions, dataset size, concurrency, percentile response times and errors. [INSERT TOOL, ENVIRONMENT AND RESULTS.]')
heading('5.7 Test Results',2); table(['Area','Result to record','Decision'],[['Functional workflows','[INSERT PASS/FAIL COUNT AND DEFECT IDS]','[INSERT ACCEPT/RETEST]'],['Usability','[INSERT COMPLETION/FEEDBACK SUMMARY]','[INSERT ACCEPT/IMPROVE]'],['Security','[INSERT FINDINGS/REMEDIATION]','[INSERT ACCEPT/BLOCK]'],['Performance','[INSERT MEASUREMENTS]','[INSERT ACCEPT/TUNE]'],['Localisation','[INSERT LANGUAGE COVERAGE AUDIT]','[INSERT ACCEPT/COMPLETE TRANSLATIONS]']])
heading('5.8 Deployment Testing',2); p('After deployment to Vercel, test the public URL, routing, static assets, authentication, database persistence, file storage behaviour, environment variables, HTTPS, logs and error paths. Vercel’s serverless filesystem is not a durable database location; verify that production database configuration and upload strategy meet the application’s needs. [INSERT DEPLOYMENT TEST DATE, URL, COMMIT AND RESULTS.]')
heading('5.9 Summary',2); p('The test plan supplies traceability for the principal functions and protects against unsupported claims. The report should be finalised only after actual outcomes and defect resolutions have been inserted.')

chapter('CHAPTER SIX: CONCLUSION AND RECOMMENDATIONS')
heading('6.1 Introduction',2); p('This chapter summarises the project, maps objectives to evidence and identifies responsible next steps.')
heading('6.2 Summary of the Project',2); p('The project developed an integrated healthcare service management web application for coordinating patient and administrative workflows through a browser. The documented solution includes identity and role management, appointment and queue workflows, provider information, service-request modules, communication features, localisation support and administration. It uses a Python/Flask architecture with Jinja, SQLAlchemy, a local SQLite configuration and a Vercel deployment configuration. The project is a web application only.')
heading('6.3 Achievement of Objectives',2)
table(['Table 6.1: Objective','Achievement evidence','Status'],[['Authentication and roles','User model, password hashing, login routes and role checks.','Implemented; deployment hardening required.'],['Appointments and queues','Appointment, slot and QueueRecord models/routes.','Implemented; validate deployed behaviour.'],['Provider/service access','Provider, pharmacy, laboratory, records and family modules.','Implemented in source; operational integrations require confirmation.'],['Information helpers','AI chat and symptom-checker routes.','Implemented as informational helpers only; not clinical diagnosis.'],['Multilingual interface','Language preferences and eight listed locale options/catalogues.','Architecture implemented; full-string coverage must be audited.'],['Administration','Admin, pharmacy, announcement and analytics routes/templates.','Implemented in source; verify permissions and reports.'],['Web deployment/version control','Vercel config; Git repository present.','Vercel configured; insert live URL and GitHub link.']])
heading('6.4 Conclusion',2); p('The project demonstrates a coherent approach to healthcare-service management on the web. Its principal contribution is the integration of service-oriented workflows within a role-based, responsive application rather than a collection of unrelated pages. The system should be assessed as a software-management platform: it can organise requests, information and communication, but it does not replace clinical judgement, emergency services, regulated payment processing or institutional governance. Completion of the verification checklist and production safeguards is essential before real-world deployment involving sensitive health data.')
heading('6.5 Recommendations',2); p('Prioritise a production database, secret management, HTTPS verification, secure upload storage, backup/retention policy, audit trails, accessibility testing and a full translation audit. Establish data-protection, consent, clinical escalation, provider verification and incident-response policies with the relevant healthcare institution before handling real patient data. Replace the internal payment-status simulation with a properly approved payment-provider integration only when the necessary business and compliance arrangements are in place.')
heading('6.6 Future Enhancements',2)
for x in ['Develop a dedicated mobile application as future work; it is not part of the current project.','Integrate approved wearable devices and patient-consented remote-monitoring workflows.','Add additional verified payment providers and transaction reconciliation.','Introduce advanced, clinically governed AI capabilities with validation, monitoring, fairness assessment and clinician oversight.','Support ambulance tracking and verified emergency dispatch integration subject to local authority approval.','Integrate additional healthcare institutions through documented interoperability agreements.','Add further languages and complete professional translation/quality assurance for all user-facing strings.']: bullet(x)

chapter('REFERENCES')
refs=[
'[1] World Health Organization. (2021). Global strategy on digital health 2020–2025. https://www.who.int/publications/i/item/9789240020924 (Accessed: [INSERT DATE]).',
'[2] MyChart is Epic. (n.d.). Find and schedule care near you. https://www.mychart.org/l/en-us/features/schedule/ (Accessed: [INSERT DATE]).',
'[3] MyChart is Epic. (n.d.). Explore MyChart. https://www.mychart.org/l/en-us/explore/ (Accessed: [INSERT DATE]).',
'[4] MyChart is Epic. (n.d.). Connect with your doctor virtually. https://www.mychart.org/l/en-us/features/virtual/ (Accessed: [INSERT DATE]).',
'[5] MyChart is Epic. (n.d.). Manage care for you and your family. https://www.mychart.org/l/en-us/features/family/ (Accessed: [INSERT DATE]).',
'[6] Pallets Projects. (n.d.). Flask documentation. https://flask.palletsprojects.com/ (Accessed: [INSERT DATE]).',
'[7] SQLAlchemy authors. (n.d.). SQLAlchemy documentation. https://docs.sqlalchemy.org/ (Accessed: [INSERT DATE]).',
'[8] Vercel. (n.d.). Python on Vercel documentation. https://vercel.com/docs/functions/runtimes/python (Accessed: [INSERT DATE]).',
'[9] GitHub Docs. (n.d.). About repositories. https://docs.github.com/repositories/creating-and-managing-repositories/about-repositories (Accessed: [INSERT DATE]).'
]
for r in refs: p(r)
p('Before submission, confirm the institution’s required referencing style and replace access-date placeholders. Add only sources actually consulted; do not add references merely to increase the list.')

chapter('APPENDICES')
for h,body in [('Appendix A: Additional Screenshots','[INSERT AUTHENTIC ADDITIONAL SCREENSHOTS, EACH WITH FIGURE NUMBER, CAPTION AND BRIEF EXPLANATION.]'),('Appendix B: Database Schema','[INSERT EXPORTED DATABASE SCHEMA OR FINAL ERD.]'),('Appendix C: Selected Source Code','[INSERT SELECTED, FORMATTED EXCERPTS: authentication/role check, appointment workflow, language selection and representative model. Do not include secrets.]'),('Appendix D: Test Results','[INSERT COMPLETED TEST EXECUTION RECORDS, DEFECT LOG AND EVIDENCE.]'),('Appendix E: GitHub Repository Information','Repository URL: [INSERT GITHUB URL]\nBranch/commit submitted: [INSERT COMMIT HASH]\nAccess arrangement: [INSERT PUBLIC/PRIVATE AND EXAMINER ACCESS METHOD].'),('Appendix F: Deployment Information','Deployed URL: [INSERT VERCEL URL]\nDeployment date: [INSERT DATE]\nEnvironment configuration summary (no secrets): [INSERT.]')]:
    heading(h,2); p(body)
heading('Final Submission Checklist',2)
for x in ['Replace all personal and institutional placeholders (name, index number, programme, department, supervisor, dates).','Confirm the precise Python version and any technologies not visible in the repository.','Insert genuine screenshots, use-case diagram, system-architecture diagram and ER diagram; update figure captions/fields.','Insert GitHub repository URL, submitted commit hash and Vercel deployment URL.','Run the stated test cases and replace every “Actual Result” and status placeholder with evidence.','Verify all feature claims against the deployed application, particularly payments, real-time updates, telemedicine and chat.','Audit every supported language across all visible user-facing text; log and correct untranslated strings.','Confirm references and access dates, then update table of contents, list of figures, list of tables and page numbers in Word.','Obtain institution-required review/approval and confirm applicable privacy, clinical governance and data-protection requirements.']: bullet(x)

# Configure headings to be page-break-aware and save.
for sname in ['Heading 1','Heading 2','Heading 3']:
    styles[sname].paragraph_format.keep_with_next=True
d.core_properties.title='Integrated Healthcare Service Management Web Application – Project Documentation'
d.core_properties.subject='University-level project report'
d.core_properties.author='[INSERT STUDENT FULL NAME]'
d.save(OUT)
print(OUT.resolve())
